apiVersion: v1
kind: Config
clusters:
- name: kube-auditing
  cluster:
    server: http://crowdsec-agent-service.crowdsec.svc:9876/audit/webhook/event
contexts:
- context:
    cluster: kube-auditing
    user: ""
  name: default-context
current-context: default-context
preferences: {}
users: []