apiVersion: v1
kind: Config
clusters:
- name: kube-auditing
  cluster:
    server: http://127.0.0.1:30000/audit/webhook/event
contexts:
- context:
    cluster: kube-auditing
    user: ""
  name: default-context
current-context: default-context
preferences: {}
users: []