container_runtime: containerd
agent:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 100Mi
  additionalAcquisition:
   - source: k8s-audit
     listen_addr: 0.0.0.0
     listen_port: 9876
     webhook_path: /audit/webhook/event
     labels:
       type: k8s-audit
  service:
    type: NodePort
    ports:
      - port: 9876
        targetPort: 9876
        nodePort: 30000
        protocol: TCP
        name: audit-wehbook
  env:
    - name: PARSERS
      value: "crowdsecurity/cri-logs"
    - name: COLLECTIONS
      value: "crowdsecurity/traefik"
    # When testing, allow bans on private networks
    - name: DISABLE_PARSERS
      value: "crowdsecurity/whitelists"
  persistentVolume:
    config:
      enabled: false
lapi:
  dashboard:
    enabled: false
  persistentVolume:
    config:
      enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 100Mi
  env:
    # For an internal test, disable the Online API
    - name: DISABLE_ONLINE_API
      value: "true"
