apiVersion: apps/v1
kind: Deployment
metadata:
  name: priv-pod
spec:
  selector:
    matchLabels:
      app: priv-pod
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: priv-pod
    spec:
      containers:
      - name: priv-pod
        image: ubuntu:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          privileged: true
        command: ["/bin/bash", "-c", "sleep 100000"]