apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: helloworld
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`helloworld.local`)
      kind: Rule
      services:
        - kind: Service
          name: helloworld
          namespace: default
          port: 5678