tls:
  enabled: true
  bouncer:
    reflector:
      namespaces: ["traefik"]
  appsec:
    tlsClientAuth: false
    reflector:
      namespaces: ["traefik"]
appsec:
  enabled: true
  acquisitions:
    - source: appsec
      listen_addr: "0.0.0.0:7422"
      path: /
      appsec_config: crowdsecurity/appsec-default
      cert_file: /etc/ssl/crowdsec-appsec-server/tls.crt
      key_file: /etc/ssl/crowdsec-appsec-server/tls.key
      labels:
        type: appsec
  env:
    - name: COLLECTIONS
      value: "crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules"
lapi:
  env:
    # For an internal test, disable the Online API
    - name: DISABLE_ONLINE_API
      value: "true"
    - name: AGENTS_ALLOWED_OU
      value: agent-ou,appsec-ou
    - name: BOUNCER_KEY_appsec
      value: "6b71a77194327e3bf00bcef884d2688c"